#
# Define assays below.
#
# Format:
#
# ["Assay"]
# ic = {internal control fluorophore for VHF assays, VQ fluorophore for HIV assays}
# assay.{fluorophore 1} = "{Internal Control or VQ}"
# assay.{fluorophore 2} = "Target 2"
# assay.{fluorophore 3} = "Target 3"
#
# # # # # # # # # # # # # # # # # # # # # # # # #

["PANDAA Ebola + Marburg"]
ic = "CY5"
assay.CY5 = "Internal Control"
assay.FAM = "EBOV"
assay.VIC = "MARV"

["PANDAA CCHFV"]
ic = "CY5"
assay.CY5 = "Internal Control"
assay.FAM = "CCHFV"

["PANDAA LASV"]
ic = "CY5"
assay.CY5 = "Internal Control"
assay.FAM = "LASV"

# # # # # # # # # # # # # # # # # # # # # # # # #

["076V 184VI"]
ic = "CY5"
assay.CY5 = "VQ"
assay.FAM = "076V"
assay.NED = "184VI"

["082AFT 084V"]
ic = "CY5"
assay.CY5 = "VQ"
assay.FAM = "84V"
assay.NED = "82AFT"
